config/routes.rb
Ticketee::Application.routes.draw do
  root :to => 'projects#index'
  resources :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, :notice => 'Project has been created'
    else
      flash.alert = 'Project has not been created.'
      render :action => 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
  end
  def edit
    @project = Project.find(params[:id])
  end
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, :notice => "Project has been updated."
    else
      flash.alert = "Project has not been updated."
      render :action => :edit
    end
  end
  def destroy
    Project.destroy params[:id]
    redirect_to projects_path, :notice => "Project has been deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title *parts
    unless parts.empty?
      content_for :title, parts.push("Ticketee").join(" - ")
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for? :title %>
      <%= yield(:title) %>
    <% else %>
      Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>


</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<h2>Projects</h2>
<ul>
  <% @projects.each do |p| %>
    <li><%= link_to p.name, p %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<% title @project.name, "Projects" %>
<h2><%= @project.name %></h2>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project", @project, :method => :delete %>